### PR TITLE
nl-NL: Translations

### PR DESCRIPTION
**Pull request by karst**

### CODE REVIEW

**Comment by karst** [comment]
@Gymnasiast could you review thisone for me?

**Comment by Gymnasiast** [comment]
I will :+1:
Can I push any necessary changes to your repo/branch (I’ll need write access for that)?

**Comment by karst** [comment]
I added you as collaborator to my fork, I think that should do the trick

**Review by Gymnasiast — APPROVED** [review]
Ziet er allemaal prima uit, heb niets hoeven aanpassen :+1:

**Comment by karst** [comment]
Perfect! Dan merge ik hem :)

**Pull request merged**
