### PR TITLE
Update Hungarian translation

### PR DESCRIPTION
**Pull request by anon569**

### CODE REVIEW

**Comment by Broxzier** [comment]
Thanks for the PR. I've asked a Hungarian friend to check and this was their feesback:

> For dodgem:
>  - Dodzsem stílus 1
>  - Dodzsem stílus 2
> 
> We don't really use the 'beat' word and also it would be 'ütem' but 'Dodzsem ütem stílus' feels super weird for me for some reason.
>
> Rest are fine

Could you adjust these, or otherwise explain how/why your translations are better already?

**Comment by anon569** [comment]
> Thanks for the PR. I've asked a Hungarian friend to check and this was their feesback:
> 
> > For dodgem:
> > 
> > * Dodzsem stílus 1
> > * Dodzsem stílus 2
> > 
> > We don't really use the 'beat' word and also it would be 'ütem' but 'Dodzsem ütem stílus' feels super weird for me for some reason.
> > Rest are fine
> 
> Could you adjust these, or otherwise explain how/why your translations are better already?

I think your friend is right. I've corrected it.

**Review by tupaschoal — APPROVED** [review]
Haven't checked the translations, but seems to cover all that is listed on OpenRCT2/Localisation#2640 currently

**Comment by karst** [comment]
I'll make sure to update this with OpenMusic and Mystic style for 0.4.7.

**Pull request merged**
