### PR TITLE
Replace dodgems style

### PR DESCRIPTION
**Pull request by karst**
I have created a new cover that's more faithful to the original as well as being a lot less boring. I hope you guys like it better too.

Old: 
https://on.soundcloud.com/wSWeN

New:
https://on.soundcloud.com/5AGgE

### CODE REVIEW

**Comment by karst** [comment]
No clue why it's failing.

**Comment by Gymnasiast** [comment]
Hm, the old one may have been more boring, but it did sound more like the original, especially with the “emerging beat” (sorry for being vague here).

**Comment by RobertWHurst** [comment]
The new one actually sounds like what I'd expect them to play at a bumpercars ride, the former sound more like a club base track.

**Comment by IntelOrca** [comment]
> No clue why it's failing.

Because you forgot to update `openrct2.music.alternative.json`

**Comment by Gymnasiast** [comment]
> The new one actually sounds like what I'd expect them to play at a bumpercars ride, the former sound more like a club base track.

Very well, let’s merge it then.

**Comment by karst** [comment]
> Because you forgot to update `openrct2.music.alternative.json`

Does it only work as `openrct2.music.alternative`?

**Comment by Gymnasiast** [comment]
> > Because you forgot to update `openrct2.music.alternative.json`
> 
> Does it only work as `openrct2.music.alternative`?

No, what IntelOrca means is that you need to modify https://github.com/OpenRCT2/OpenMusic/blob/master/openrct2.music.alternative.json , since you changed the ID of your dodgems style.

**Comment by karst** [comment]
Ohhh gotcha, I am stupid lol, how did I not notice that file.

**Review by Gymnasiast — APPROVED** [review]

**Pull request merged**
