### PR TITLE
Add extraterrestrial style

### PR DESCRIPTION
**Pull request by karst**
Let me know if there's anything that needs changing, but I think I got everything correctly.

### CODE REVIEW

**Review by tupaschoal — COMMENTED** [review]
TBH I think I like this better than the original, which sounded a more on the spooky/Halloween side than something from space.

I just think the loop feels a little unpleasant, as the music grows as it progresses and then "resets" all of a sudden at the end, maybe it should slow down on some of the effects before it loops (?). Being a non-musician makes it very hard for me to explain what I want :D

**Comment by karst** [comment]
I do get what you mean, ill make it a bit longer to transition back to less distorted and such.

**Review by tupaschoal — APPROVED** [review]
Honestly I couldn't tell the difference between the last and penultimate commit, but I like the longer version to loop in a smoother manner and I'm satisfied with the music :D

**Review by tupaschoal — APPROVED** [review]
I don't know what changed, but it still sounds great :P

**Comment by karst** [comment]
haha, the bass that comes in was a bit too harsh for my liking at the start, so I made it so the top-end frequencies come in halfway through the song. Gives a bit more tension.

**Comment by ZehMatt** [comment]
The audio file is quite big, it's 20MiB for 3min audio, if we have a few of them then its getting quite big pretty fast, anything we can do about that?

Edit: The music is pretty good also.

**Comment by karst** [comment]
The FLAC is just the size of the file in this directory. It gets converted to a OGG Vorbis file. It's being saved in FLAC for if we ever want a higher quality pack option to be available. You can expect the size included in the game to be a bit under 1mb.

**Comment by ZehMatt** [comment]
> The FLAC is just the size of the file in this directory. It gets converted to a OGG Vorbis file. It's being saved in FLAC for if we ever want a higher quality pack option to be available. You can expect the size included in the game to be a bit under 1mb.

Fair enough

**Comment by karst** [comment]
It would be nice if this could be merged and a new release could be made so this and Blizzard style could be part of the new release. 

It seems MacOS still has some issues with getting ahold of the OpenMusic and OpenSound files. I believe Linux was fixed with a very recent PR.

**Pull request merged**
