### PR TITLE
Add Rock style 4 ride music style

### PR DESCRIPTION
**Pull request by karst**
Submitted by Blackend Blue

### CODE REVIEW

**Review by tupaschoal — COMMENTED** [review]
I really like it, though that's easy since rock is more on my taste. I wonder whether it's a bit more towards metal than rock 🤣

**Comment by karst** [comment]
Blackend loves to make screamo metal too so you can definitely hear that influence hahaha

**Comment by karst** [comment]
I can always rename it to Metal style 1 if this is prefered

**Comment by tupaschoal** [comment]
> I can always rename it to Metal style 1 if this is prefered

Not needed!

**Comment by karst** [comment]
There's also the possibility of calling it Punk style, but I think Rock style 4 will do.

Is there anything I forgot/messed up in this PR or does it look all good?

**Comment by tupaschoal** [comment]
LGTM

**Pull request merged**
