### PR TITLE
Add Galaxy Style

### PR DESCRIPTION
**Pull request by karst**
Adds fallback song for Space Style.

Song isn't final per se. Feedback is welcome!

### CODE REVIEW

**Comment by IntelOrca** [comment]
Not sure we should be commit large .wav files to this repo. At least consider FLAC.

**Comment by karst** [comment]
Let me check how much the difference in file size between WAV & FLAC is.

**Comment by karst** [comment]
> Not sure we should be commit large .wav files to this repo. At least consider FLAC.

FLAC is 51MB (BItrate: 1610kbps) compared to the WAV's 67MB (bitrate: 2116kbps)

It's up to you what you'd prefer

**Comment by IntelOrca** [comment]
@karst That is still an improvement, why do you think using flac is a disadvantage?

**Comment by karst** [comment]
I have done some research on it and you are right. It seems flac would reduce the filesize if I would turn the compression up, this should be nearly unnoticable. So should be fine. I'll make sure to update this PR with a FLAC file

**Comment by IntelOrca** [comment]
This PR has a .wav which is 8-bit 22050 (10 MiB).
And also a flac which is 32-bit 44100 (50 MiB).

If I run `ffmpeg -i galaxy.wav galaxy.flac`, I get a much smaller flac file, 5 MiB. This is what you need to upload.

**Comment by karst** [comment]
This is the lowest size FL allows me to render FLAC.
I will have to see what I can do with Audacity

**Comment by karst** [comment]
Sadly Audacity does not support FLAC rendering. :C

**Comment by karst** [comment]
My preference for using audio in game would still be with OGG Vorbis, or OGG Opus. This is really small with a decent sound quality. For the soundtrack I do think in the lowest form I rendered right now (the lowest that's available on FL) is a good idea for the renders of the Soundtrack compilation. It's good to have high res versions of the songs for that in the repository.

**Comment by Broxzier** [comment]
What about sharing the source files instead of the rendered audio files? Or is the software you use for rendering (FL Studio?) not freeware?

**Comment by karst** [comment]
I can share the FLP, but FL isn't freeware (full version, is 1000€ without discounts) and I am using VSTs. Beside that because I use several samples (which are in WAV) the file size of the FLP will potentially be bigger than the final output

**Comment by IntelOrca** [comment]
> Sadly Audacity does not support FLAC rendering. :C

`ffmpeg` does, so that is all you need. It is a bit more advanced in that it is a command line application, but it does the job at converting .wav to .flac.

> My preference for using audio in game would still be with OGG Vorbis, or OGG Opus. This is really small with a decent sound quality. For the soundtrack I do think in the lowest form I rendered right now (the lowest that's available on FL) is a good idea for the renders of the Soundtrack compilation. It's good to have high res versions of the songs for that in the repository.

If we ever use a lossy format, we still want to keep the original version in this repo. FLAC preserves this.

**Comment by karst** [comment]
I will check if getting it down even further will not make it sound like the 10mb WAV included in with the object file, because if that's the case you have massive loss in quality, say you'd ever want to distrubute the soundtrack as an album like alot of games do (and is very much requested).

In game you won't notice it, but if you play it through any regular media player you will definitely notice the dip in quality.

**Comment by karst** [comment]
If I get the FLAC sized down to 5mb you like you said it kills the depth of a tune entirely, making it useless for making a distributable soundtrack. I cannot go lower than the flac I have included (28mb) with severely losing audio quality. What is the reason to keep the size down in this directory? Might it be a better option to create a shared Google Drive folder we dump these in and then include the link in the rendering guide,txt (or md version of it?). If you want to lower the file size without having a audible difference for non-audiophiles (so without trained ears) MP3 or OGG (Thisone is opensource, so probably prefered) is the way to go. But for the soundtrack I do recommend having the files in FLAC or WAV (44100 Sample Rate).

**Comment by ExileFox** [comment]
Audacity DOES support FLAC rendering, but I believe ffmpeg needs to be
registered somehow. I don't know the details, but at least on my linux
machine I do have the option under Export -> Export Audio -> Type: [dropdown list]

it's buried though. https://user-images.githubusercontent.com/2000703/163279368-03737a89-d9ff-4e7b-8e08-9d6acbf35799.jpg

**Comment by IntelOrca** [comment]
@karst no, export your tune as .wav with the quality settings you are happy with. Then convert to FLAC. Converting to FLAC should not degrade the original .wav quality because it is a lossless codec.

**Comment by karst** [comment]
> @karst no, export your tune as .wav with the quality settings you are happy with. Then convert to FLAC. Converting to FLAC should not degrade the original .wav quality because it is a lossless codec.

I have done this and it reduced the filesize from 67MB (wav) to 27MB (flac) so it's definitely a good reduction

**Review by RobertWHurst — APPROVED** [review]

**Comment by IntelOrca** [comment]
You have uploaded the .wav file again, please remove this.

**Comment by karst** [comment]
Oh, it seems i have forgotten to update this PR. I'll work on it tonight

**Comment by karst** [comment]
There we go. Fixed that for ya. I think the mix is good how it is, but if you hear anything unpleasant let me know!

**Pull request merged**
